version: '3'
services:
  nginx:
    image: nginx:1.13.5-alpine
    container_name: cake_nginx
    ports:
      - '8080:80'
    volumes:
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/htdocs:/var/www/html
      # root          /var/www/html/webroot

  php:
    container_name: cake_php
    build: build/cake_php
    volumes:
      - ./data/htdocs:/var/www/html

  mysqldb:
    image: mysql:5.6
    container_name: cake_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cake
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      # - ./config/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql:/var/lib/mysql
