apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: buildkitd
  name: buildkitd
spec:
  selector:
    matchLabels:
      app: buildkitd
  template:
    metadata:
      labels:
        app: buildkitd
    spec:
      containers:
      - image: moby/buildkit
        args:
          - --addr
          - tcp://0.0.0.0:1234
        name: buildkitd
        ports:
          - containerPort: 1234
        securityContext:
          privileged: true
