version: '3.7'
services:

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - "8083:80"
    tty: true
    volumes:
      - ./nginx/conf/proxy.conf:/etc/nginx/conf.d/default.conf
    restart: always
    links:
      - nginx1:nginx1.docker.local
      - nginx2:nginx2.docker.local

  nginx1:
    image: nginx:alpine
    container_name: nginx1
    tty: true
    volumes:
      - ./nginx/html1:/app
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    tty: true
    volumes:
      - ./nginx/html2:/app
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
