# apiVersion: v1
# kind: Namespace
# metadata:
#   name: sample
#   labels:
#     name: sample
# ---

# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: hello-nginx
#   # namespace: sample
# spec:
#   rules:
#   - http:
#       paths:
#       - backend:
#           serviceName: nginx-svc
#           servicePort: 7777

# ---

apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  # namespace: sample
spec:
  type: LoadBalancer
  selector:
    app: nginx-proxy
  ports:
  - name: http
    port: 7777
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deploy
  # namespace: sample
  labels:
    app: nginx-proxy
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: hello-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
    