version: '3.7'

services:
  server:
    build: .
    container_name: server
    working_dir: "/tmp"
    volumes:
      - /c/Users/Public/docker-shared:/tmp/shared
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "80:80"
      - "8082:8082"
      - "22:22"
    privileged: true
    tty: true # Can keep running
