
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-master-nodeport
spec:
  type: NodePort
  ports:
    - name: "ssh-port"
      protocol: "TCP"
      nodePort: 30022
      port: 22
      targetPort: 22
  selector:
    app: jenkins-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-pod
  template:
    metadata:
      labels:
        app: jenkins-pod
    spec:
      containers:
        - name: jk2
          image: jenkins-master:blank
          imagePullPolicy: IfNotPresent
          tty: true
          volumeMounts:
            - name: jenkins-storage
              mountPath: /app
          ports:
            - containerPort: 22
          lifecycle:
            postStart:
              exec:
                command:
                - sh
                - -c
                - "/etc/init.d/sshd start"
      restartPolicy: Always
      volumes:
        - name: jenkins-storage
          emptyDir: {}
