---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ansible
  name: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-pod
  template:
    metadata:
      labels:
        app: ansible-pod
    spec:
      containers:
      - name: control
        image: ansible_controller:0.1
        tty: true
        imagePullPolicy: IfNotPresent
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: svc-jenkins-master
  labels:
    run: svc-jenkins-master
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    run: jenkins-pod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-pod
  template:
    metadata:
      labels:
        app: jenkins-pod
    spec:
      containers:
      - name: jk2
        image: jenkins-master:blank
        tty: true
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - "/etc/init.d/sshd start"
      restartPolicy: Always
