apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: nginx1-svc
          servicePort: 7020

---
apiVersion: v1
kind: Service
metadata:
  name: nginx1-svc
spec:
  type: NodePort
  selector:
    app: nginx-proxy
  ports:
  - name: http
    protocol: TCP
    port: 7020
    targetPort: 80

---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-deployment
  labels:
    app: nginx-proxy
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      containers:
      - name: hello-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
    